---
title: "Day 2 Exercise Finn Qiao"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
gapminder <- read.csv(here::here("data", "gapminder5.csv"))
```

```{r}
str(gapminder)
```

## converting factors to characters
```{r}
gapminder$country <- as.character(gapminder$country)
gapminder$continent <- as.character(gapminder$continent)
str(gapminder)
```

```{r}
obs <- 1:nrow(gapminder)

for (i in obs) {
  gapminder[i,'gdp'] <- gapminder[i,'pop'] * gapminder[i,'gdpPercap']
}
```

## creating logged variables with a for loop
```{r}
for (i in obs) {
  gapminder[i, 'log_gdpPercap'] <- log(gapminder[i,'gdpPercap'])
  gapminder[i, 'log_pop'] <- log(gapminder[i,'pop'])
}
```

```{r}
years <- unique(gapminder$year)

for (i in years) {
  mean_le <- mean(gapminder$lifeExp[gapminder$year == i],
                  na.rm = T)
  print(paste0(i, ': ', mean_le))
}
```

```{r}
continents <- unique(gapminder$continent)

for (i in continents) {
  mean_cont <- mean(gapminder$lifeExp[gapminder$continent == i], 
                    na.rm = T)
  print(paste0(i, ': ', mean_cont))
}
```

```{r}
for (i in continents) {
  print(paste0('Continent: ', i))
  for (j in years) {
    mean_le <- mean(gapminder$lifeExp[gapminder$continent == i & gapminder$year == j], na.rm = T)
    print(paste0(j, ": ", mean_le))
  }
}
```

## double for loop
```{r}
for (i in continents) {
  print(paste0('Continent: ', i))
  for (j in years) {
    mean_le <- sd(gapminder$lifeExp[gapminder$continent == i & gapminder$year == j], na.rm = T)
    print(paste0(j, ": ", mean_le))
  }
}
```

## apply, lapply, sapply
```{r}
vars <- gapminder[, c("lifeExp", "pop", "gdpPercap")]
apply(vars, 2, mean)
```

```{r}
lapply(gapminder, mean)
```

```{r}
sapply(gapminder, mean)
```

```{r}
sapply(years, function(x) mean(gapminder$lifeExp[gapminder$year == x]))
```

```{r}
i <- 1952

while (i < 1987) {
  sd_le <- sd(gapminder$lifeExp[gapminder$year == i])
  print(paste0(i, ": ", sd_le))
  i <- i+5
}
```

```{r}
i <- 1987

while (i <= 2002) {
  sd_le <- sd(gapminder$lifeExp[gapminder$year == i])
  print(paste0(i, ": ", sd_le))
  i <- i+5
}
```

```{r}
year_lim <- 1987

for (i in unique(gapminder$year)){
  if (i >= year_lim) {
    mean_pop <- mean(gapminder$pop[gapminder$year == i])
    print(paste0(i, ": ", mean_pop))
  }
  else {
    print("Condition not met!")
  }
}
```

```{r}
getvalues <-
  function(df, variable = "continent") {
    vals <- unique(df[[variable]])
    print(paste0(variable, ': ', vals))
  }
```

```{r}
report_mean_sd <- 
  function(df, variable, country) {
    var <- gapminder[[variable]][gapminder$country == country]
    m_le <- mean(var)
    sd_le <- sd(var)
    cat("Country: ", country,
        "\nMean Life Expectancy: ", m_le,
        "\nSD Life Expectancy: ", sd_le)
  }

report_mean_sd(gapminder, "lifeExp", "Albania")
```

```{r}
report_stuff <-
  function(df, variable, continent) {
    var <- gapminder[[variable]][gapminder$continent == continent]
    mean_cont <- mean(var) 
    median_cont <- median(var)
    min_cont <- min(var)
    max_cont <- max(var)
    cat("Continent: ", continent,
        "\nMean: ", mean_cont,
        "\nMedian: ", median_cont,
        "\nMin: ", min_cont,
        "\nMax: ", max_cont
    )
  }

report_stuff(gapminder, "lifeExp", "Asia")
```

```{r}
viz_lm <- 
  function(df, dv, iv, year) {
    dat <- df[df[["year"]] == year, ]
    y <- log(dat[[dv]])
    x <- log(dat[[iv]])
    fit <- lm(y~x)
    plot(y ~ x, main = year, xlab = iv, ylab = dv)
    lines(x, predict(fit), col = "blue")
  }
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

