---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
gapminder <- read.csv(here::here("data", "gapminder5.csv"))
```

```{r}
str(gapminder)
```

## converting factors to characters
```{r}
gapminder$country <- as.character(gapminder$country)
gapminder$continent <- as.character(gapminder$continent)
str(gapminder)
```

```{r}
obs <- 1:nrow(gapminder)

for (i in obs) {
  gapminder[i,'gdp'] <- gapminder[i,'pop'] * gapminder[i,'gdpPercap']
}
```

## creating logged variables with a for loop
```{r}
for (i in obs) {
  gapminder[i, 'log_gdpPercap'] <- log(gapminder[i,'gdpPercap'])
  gapminder[i, 'log_pop'] <- log(gapminder[i,'pop'])
}
```

```{r}
years <- unique(gapminder$year)

for (i in years) {
  mean_le <- mean(gapminder$lifeExp[gapminder$year == i],
                  na.rm = T)
  print(paste0(i, ': ', mean_le))
}
```

```{r}
continents <- unique(gapminder$continent)

for (i in continents) {
  mean_cont <- mean(gapminder$lifeExp[gapminder$continent == i], 
                    na.rm = T)
  print(paste0(i, ': ', mean_cont))
}
```

```{r}
for (i in continents) {
  print(paste0('Continent: ', i))
  for (j in years) {
    mean_le <- mean(gapminder$lifeExp[gapminder$continent == i & gapminder$year == j], na.rm = T)
    print(paste0(j, ": ", mean_le))
  }
}
```

## double for loop
```{r}
for (i in continents) {
  print(paste0('Continent: ', i))
  for (j in years) {
    mean_le <- sd(gapminder$lifeExp[gapminder$continent == i & gapminder$year == j], na.rm = T)
    print(paste0(j, ": ", mean_le))
  }
}
```

apply, lapply, sapply
```{r}

```

